### ISSUE TITLE
ZenHub: Popup has scrollbars

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6014]
**Describe the issue you encountered:**
The ZenHub extension popup has unnecessary scrollbars.

**Expected behavior:**
There should not be any scrollbars on the popup.

**Brave Version:** 0.12.11

**Screenshot if needed:**
![image](https://cloud.githubusercontent.com/assets/815158/20868375/c5a7c628-ba1f-11e6-93be-3405714ed552.png)

**Any related issues:** #5998, #6002

**Comment by jonathansampson** [comment]
The above is caused by the following CSS:

```css
.zh-menu-header .zh-menu-items {
  position: absolute;
  right: -13;
  top: 8;
}
```

This causes the container housing the _Dashboard_, _Help_, and _Sign Out_ links to be pushed 13 pixels over the right-edge of the viewport. This results in scrollbars.

Setting `overflow-x: hidden` on the `html` element resolves.
